# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
